Add missing header for getuid()
Amends de5f419e0c379ce6096ca9e63976d13a3d2b5165 and
c54441c7e98dea3ec1ac3f9fe2f955e588da310c

See also 534318c449a5ddbd409da428ab2aaf4049452040 (was in src/mainwindow.cpp)

Fixes build error:
src/unitmodel.cpp:454:86: error: ‘getuid’ was not declared in this scope

Signed-off-by: Andreas Sturmlechner <asturm@gentoo.org>